name: Non-Prod-Pipeline

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      environment:      
        required: true
        type: string

permissions:
  contents: read
  statuses: write

env:
  ACCOUNT_ID: 522534289017

jobs:
  non-prod-pipeline:
    runs-on: self-hosted

    steps:
    # ---------------- CHECK COMMIT STATUSES ----------------
    - name: Validate Commit Statuses
      run: |
        COMMIT=${{ inputs.commit_id }}
        REPO=${{ github.repository }}
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        ENV=${{ inputs.environment }}

        curl -s -H "Authorization: Bearer $TOKEN" \
        https://api.github.com/repos/$REPO/commits/$COMMIT/status \
        > status.json

        if [ "$ENV" == "dev" ]; then
          REQUIRED=("UNIT_TEST" "NPM_AUDIT" "DOCKER_BUILD")
        elif [ "$ENV" == "uat" ]; then
          REQUIRED=("UNIT_TEST" "NPM_AUDIT" "DOCKER_BUILD" "DEV_DEPLOY")
        else
          echo "Invalid environment"
          exit 1
        fi

        echo "Required checks for $ENV:"
        printf '%s\n' "${REQUIRED[@]}"

        for CONTEXT in "${REQUIRED[@]}"; do
          STATE=$(jq -r ".statuses | map(select(.context==\"$CONTEXT\")) | .[0].state" status.json)

          echo "$CONTEXT -> $STATE"

          if [ "$STATE" != "success" ]; then
            echo "❌ $CONTEXT failed. Cannot promote."
            exit 1
          fi
        done

        echo "✅ Promotion allowed for $ENV"

    # ---------------- SELECT CLUSTER DYNAMICALLY ----------------
    # - name: Set cluster name
    #   run: |
    #     if [ "${{ inputs.environment }}" == "qa" ]; then
    #       echo "CLUSTER=robomart-qa" >> $GITHUB_ENV
    #     elif [ "${{ inputs.environment }}" == "sit" ]; then
    #       echo "CLUSTER=robomart-sit" >> $GITHUB_ENV
    #     elif [ "${{ inputs.environment }}" == "uat" ]; then
    #       echo "CLUSTER=robomart-uat" >> $GITHUB_ENV
    #     else
    #       echo "Invalid environment"
    #       exit 1
    #     fi

    # ---------------- AWS AUTH ----------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # ---------------- EKS LOGIN ----------------
    - name: Authenticate to EKS
      run: | # $CLUSTER
        aws eks update-kubeconfig --region us-east-1 --name  robomart-dev 
        kubectl get nodes

    # ---------------- CHECKOUT DEPLOY REPO ----------------
    - name: Checkout Deploy Repo
      uses: actions/checkout@v4
      with:
        repository: azharmd-dev/catalogue-deploy

    # ---------------- DEPLOY ----------------
    - name: Deploy to Selected Environment
      id: deploy_check
      run: |
        helm upgrade --install ${{ inputs.component }} \
          -f values-dev.yaml \
          --set deployment.imageVersion=${{ inputs.commit_id }} \
          -n ${{ inputs.project }} \
          --atomic --wait --timeout=5m .
          
        # helm upgrade --install ${{ inputs.component }} \
        #   -f values-${{ inputs.environment }}.yaml \
        #   --set deployment.imageVersion=${{ inputs.commit_id }} \
        #   -n ${{ inputs.project }} \
        #   --atomic --wait --timeout=5m .


    # - name: DEPLOY status
    #   if: always()
    #   uses: azhardevmd/workflows/.github/actions/set-commit-status@main
    #   with:
    #     state: ${{ steps.deploy_check.outcome }}
    #     context: "${{ inputs.environment }}-DEPLOY"
    #     status_description: "${{ inputs.environment }} ${{ steps.deploy_check.outcome }}"
    #     target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
    # Convert outcome → valid GitHub state
    - name: Convert outcome to GitHub status
      id: status_map
      if: always()
      run: |
        if [ "${{ steps.deploy_check.outcome }}" == "success" ]; then
          echo "state=success" >> $GITHUB_OUTPUT
        else
          echo "state=failure" >> $GITHUB_OUTPUT
        fi

    # Map environment → fixed context name
    - name: Set DEPLOY commit status
      if: always()
      uses: azhardevmd/workflows/.github/actions/set-commit-status@main
      with:
        state: ${{ steps.status_map.outputs.state }}
        context: ${{ inputs.environment == 'uat' && 'UAT_DEPLOY' || 'DEV_DEPLOY' }}
        status_description: "${{ inputs.environment }} deploy ${{ steps.deploy_check.outcome }}"
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}